# Autogenerated file.
# Do not edit.
# Do not change location.
 
set(TESTSESSION_INCLUDE_DIRS "/home/juan/pepper_ws/libqi/tests/messaging/libtestsession;/home/juan/pepper_ws/libqi/BUILD/include;/home/juan/pepper_ws/libqi;/home/juan/boost_1_59_0;/usr/include;/usr/include;/home/juan/boost_1_59_0;/usr/include;/usr/include;/usr/include;/home/juan/pepper_ws/libqi/BUILD/tests/gtest/src/gtest/include;/home/juan/pepper_ws/libqi/BUILD/tests/gmock/src/gmock/include;/home/juan/pepper_ws/libqi;/home/juan/pepper_ws/libqi/tests/.;/home/juan/pepper_ws/libqi;/home/juan/pepper_ws/libqi/compat;/home/juan/pepper_ws/libqi/BUILD/include;/home/juan/boost_1_59_0;/usr/include;/home/juan/pepper_ws/libqi/tests/messaging/libtestsession/.;/home/juan/pepper_ws/libqi;/home/juan/pepper_ws/libqi/compat;/home/juan/pepper_ws/libqi/BUILD/include;/home/juan/boost_1_59_0;/usr/include" CACHE INTERNAL "" FORCE)
 
set(TESTSESSION_LIBRARIES "general;/home/juan/pepper_ws/libqi/BUILD/sdk/lib/libtestsession.a" CACHE INTERNAL "" FORCE)
 
set(TESTSESSION_TARGET "testsession" CACHE INTERNAL "" FORCE)

set(TESTSESSION_PACKAGE_FOUND "TRUE" CACHE INTERNAL "" FORCE)

set(TESTSESSION_DEPENDS "QI;BOOST;BOOST_ATOMIC;BOOST_DATE_TIME;BOOST_FILESYSTEM;BOOST_REGEX;BOOST_PROGRAM_OPTIONS;OPENSSL;BOOST_LOCALE;BOOST_THREAD;BOOST_CHRONO;BOOST_SYSTEM;PTHREAD;DL;RT" CACHE INTERNAL "" FORCE)
 